name: Deploy to Firebase

on:
  push:
    branches:
      - main # Ejecutar el workflow al hacer push a la rama 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest # Cambiar a 'ubuntu-latest' si no es estrictamente necesario usar Windows

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Cambia esto según tu versión de Node.js

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn install

      - name: Build Application
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase
        run: firebase login:ci --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Select Firebase Project
        run: firebase use --add deploy-2178d

      - name: Deploy to Firebase
        run: firebase deploy

      - name: Success Message
        if: ${{ success() }}
        run: echo 'Despliegue exitoso en Firebase.'

      - name: Failure Message
        if: ${{ failure() }}
        run: echo 'El despliegue ha fallado.'
